language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -y install python3-pip
install:
  - pip3 install flit
  - flit install --deps all .
script:
  - python --version
  - which python
  - manly --version
  - py.test
